language: python

python:
  - 3.6.3

services: postgresql

env:
  - DJANGO=2.0.5

before_install:
  - export DJANGO_SETTINGS_MODULE=controller.settings
  - export PYTHONPATH=$HOME/builds/guilehm/Expense-Control-System
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py test
  - isort --check-only
  - flake8
