# Generated by Django 2.0.8 on 2018-08-20 23:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20180517_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'owner')},
        ),
    ]
