# Generated by Django 2.0.5 on 2018-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180509_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashing',
            name='when',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='when',
            field=models.DateField(),
        ),
    ]
