# Generated by Django 2.0.5 on 2018-05-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180509_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='acc_number',
            new_name='account_number',
        ),
    ]
