# Generated by Django 2.0.5 on 2018-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20180509_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='bank/logos'),
        ),
    ]
