# Generated by Django 2.0.5 on 2018-05-11 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20180510_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=3)),
                ('img', models.ImageField(blank=True, null=True, upload_to='bank/logos')),
            ],
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='img',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='name',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.Bank'),
            preserve_default=False,
        ),
    ]
