# Generated by Django 2.0.5 on 2018-05-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20180510_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
