# Generated by Django 2.0.5 on 2018-05-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='core.Tag'),
        ),
    ]
