# Generated by Django 2.0.5 on 2018-05-10 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='competition_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='competition_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
