# Generated by Django 2.0.5 on 2018-05-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180510_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='slug',
        ),
        migrations.AlterField(
            model_name='expense',
            name='competition_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='competition_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
