# Generated by Django 2.0.5 on 2018-08-04 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180518_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
